[workspace]
authors = ["APS Spectroscopy Group"]
channels = ["conda-forge"]
name = "experiment"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
notebook = "jupyter lab analysis.ipynb"

[dependencies]
matplotlib = ">=3.10.8,<4"
numpy = ">=1.26.4,<2"
xraylarch = ">=2025.2.2,<2026"
h5py = ">=3.15.1,<4"
hdf5plugin = ">=6.0.0,<7"
tiled = ">=0.2.1,<0.3"
pandas = ">=2.3.3,<3"
scipy = ">=1.16.3,<2"
xraydb = ">=4.5.8,<5"
jupyter = ">=1.1.1,<2"
pixi-kernel = ">=0.7.0,<0.8"
papermill = ">=2.6.0,<3"
jupyterlab-h5web = ">=12.5.0,<13"
mergedeep = ">=1.3.4,<2"
ipympl = ">=0.9.8,<0.10"
tomlkit = ">=0.13.3,<0.14"

[pypi-dependencies]
hollowfoot = ">=0.4.0, <1.0"
